### ISSUE TITLE
希望开发出只看#alias #var名称的功能

### ISSUE THREAD

**Issue by lx-simon** [mudclient/paotin#1]
有时候，玩家定义的alias功能太过丰富，一时想找一个alias的名称(类似直接键入#help)，使用
tintin直接键入 #alias会出现一堆alias名称与其内容，如果内容简略还好，定义的功能丰富一些，
alias的内容会导致刷屏，信息全部揉在一起，也没有格式，用户也不会去看它。
**强烈建议：对于多行的alias将其内容省略 (var 同理)**

**Comment by dzpao** [comment]
做了三个功能：

* xtt.ListAlias 查别名
* xtt.ListVar 查变量
* xtt.ListFunc 查函数

用法都差不多，分别有三种用法：

* xtt.ListXXX 默认显示全部内容，但只包括 PaoTin++ 认为适合公开的内容
* xtt.ListXXX all 强制显示全部内容，可能有些会有些乱。注意这里的 `all` 就是单词本身。
* xtt.ListXXX keyword 可以模糊查询，支持正则表达式。注意这里的 `keyword` 要替换成你的查询关键词。
